export const USER = "http://localhost:3000/Usuarios"
// export const USER = "https://usuarios-peach-tau.vercel.app/Usuarios"
export const GUAD = "https://productos-delta.vercel.app/Guajolotas"
export const BEBIDA = "https://productos-delta.vercel.app/Bebidas"
export const TAMAL = "https://productos-delta.vercel.app/Tamales" 
